import AllSetCore
import AppKit
import CryptoKit
import UniformTypeIdentifiers
import Vision

/// Records what's copied, and puts items back on the clipboard (and pastes
/// them) when chosen.
@MainActor
final class ClipboardMonitor {
    private let services: AppServices
    private var changeCount = NSPasteboard.general.changeCount
    /// The change All Set made itself, which shouldn't be recorded again.
    private var ownChangeCount = -1
    private var timer: Timer?

    /// nspasteboard.org markers that password managers and other apps use for
    /// secrets and throwaway data.
    private static let privateTypes = Set([
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "de.petermaurer.TransientPasteboardType",
    ].map { NSPasteboard.PasteboardType(rawValue: $0) })

    init(services: AppServices) {
        self.services = services
    }

    /// macOS doesn't announce clipboard changes, so check a couple of times a
    /// second, less often on battery, in Low Power Mode or when hot (the
    /// policy's pace); it's a single number comparison, but each check wakes the Mac.
    func start() {
        guard timer == nil else { return }
        schedule()
        observe({ [services] in services.ui.performance.clipboardInterval }) { [weak self] _ in self?.schedule() }
    }

    private func schedule() {
        timer?.invalidate()
        let interval = services.ui.performance.clipboardInterval
        let timer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.check() }
        }
        timer.tolerance = interval / 2
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    private func check() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != changeCount else { return }
        changeCount = pasteboard.changeCount
        guard services.clipboard.settings.isEnabled, changeCount != ownChangeCount else { return }
        guard Set(pasteboard.types ?? []).isDisjoint(with: Self.privateTypes) else { return }
        let source = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        if let source, services.clipboard.settings.ignoredApps.contains(source) { return }
        if let cgImage = copiedImage(pasteboard) {
            // Scaling and encoding a big screenshot takes a moment; not on the main thread.
            let directory = services.clipboard.imageDirectory
            let date = Date.now
            Task { [weak self] in
                let saved = await Task.detached(priority: .utility) { Self.saveImage(cgImage, in: directory) }.value
                guard let self, let (name, size) = saved else { return }
                services.clipboard.add(ClipboardItem(kind: .image, imageFile: name, imageSize: size,
                                                     sourceBundleID: source, date: date))
            }
        } else if let item = read(pasteboard, source: source) {
            services.clipboard.add(item)
        }
    }

    /// The picture on the clipboard, when a picture is what was copied.
    private func copiedImage(_ pasteboard: NSPasteboard) -> CGImage? {
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return nil
        }
        let types = pasteboard.types ?? []
        guard types.contains(.png) || types.contains(.tiff) else { return nil }
        let string = pasteboard.string(forType: .string)
        // Copying an image in a browser also puts its address on the clipboard;
        // the picture is what matters.
        let stringIsJustAddress = string.map { ClipboardItem.text($0, sourceBundleID: nil).kind == .link } ?? true
        guard string == nil || string?.isEmpty == true || stringIsJustAddress else { return nil }
        return NSImage(pasteboard: pasteboard)?.cgImage(forProposedRect: nil, context: nil, hints: nil)
    }

    private func read(_ pasteboard: NSPasteboard, source: String?) -> ClipboardItem? {
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return ClipboardItem(kind: .files, fileURLs: urls, sourceBundleID: source)
        }
        let string = pasteboard.string(forType: .string)
        if let string, !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            // Very long copies (a whole log file) are kept, but not forever long.
            return ClipboardItem.text(String(string.prefix(100_000)), sourceBundleID: source)
        }
        return nil
    }

    /// Writes a screen-sized PNG named by its content; nil if it couldn't be.
    private nonisolated static func saveImage(_ cgImage: CGImage, in directory: URL) -> (String, CGSize)? {
        let longest = max(cgImage.width, cgImage.height)
        let scale = longest > 2400 ? 2400 / Double(longest) : 1
        let width = max(Int(Double(cgImage.width) * scale), 1)
        let height = max(Int(Double(cgImage.height) * scale), 1)
        guard let context = CGContext(data: nil, width: width, height: height, bitsPerComponent: 8, bytesPerRow: 0,
                                      space: CGColorSpace(name: CGColorSpace.sRGB)!,
                                      bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue) else { return nil }
        context.interpolationQuality = .high
        context.draw(cgImage, in: CGRect(x: 0, y: 0, width: width, height: height))
        guard let scaled = context.makeImage(),
              let png = NSBitmapImageRep(cgImage: scaled).representation(using: .png, properties: [:]) else { return nil }
        // Named by content, so copying the same picture again finds the earlier copy.
        let name = SHA256.hash(data: png).prefix(12).map { String(format: "%02x", $0) }.joined() + ".png"
        let file = directory.appendingPathComponent(name)
        if !FileManager.default.fileExists(atPath: file.path) {
            guard (try? png.write(to: file)) != nil else { return nil }
        }
        return (name, CGSize(width: cgImage.width, height: cgImage.height))
    }

    // MARK: Using items

    /// Puts an item back on the clipboard and moves it to the top of history.
    func copy(_ item: ClipboardItem) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        switch item.kind {
        case .text, .link:
            pasteboard.setString(item.text ?? "", forType: .string)
        case .image:
            if let url = services.clipboard.imageURL(item), let image = NSImage(contentsOf: url) {
                pasteboard.writeObjects([image])
            }
        case .files:
            pasteboard.writeObjects((item.fileURLs ?? []) as [NSURL])
        }
        ownChangeCount = pasteboard.changeCount
        changeCount = pasteboard.changeCount
        services.clipboard.add(item)
    }

    /// Copies, then pastes into the app in front by pressing ⌘V for it, which
    /// needs Accessibility permission. Without it, the item is just copied.
    func paste(_ item: ClipboardItem) {
        copy(item)
        guard services.clipboard.settings.pasteOnSelect, Accessibility.isTrusted else { return }
        Task {
            // Let the picker close and the previous window take keys again.
            try? await Task.sleep(for: .milliseconds(120))
            Self.pressCommandV()
        }
    }

    private static func pressCommandV() {
        let source = CGEventSource(stateID: .combinedSessionState)
        let keyV: CGKeyCode = 0x09
        let down = CGEvent(keyboardEventSource: source, virtualKey: keyV, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: keyV, keyDown: false)
        down?.flags = .maskCommand
        up?.flags = .maskCommand
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
    }

    /// Reads the text in an image item on this Mac and copies it. False when
    /// no text was found.
    func copyText(from item: ClipboardItem) async -> Bool {
        guard let url = services.clipboard.imageURL(item), let text = await TextRecognizer.text(in: url), !text.isEmpty else {
            return false
        }
        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString(text, forType: .string)
        return true
    }
}

/// On-device text recognition with the Vision framework.
enum TextRecognizer {
    static func text(in url: URL) async -> String? {
        await Task.detached(priority: .userInitiated) { () -> String? in
            let request = VNRecognizeTextRequest()
            request.recognitionLevel = .accurate
            request.usesLanguageCorrection = true
            request.automaticallyDetectsLanguage = true
            do {
                try VNImageRequestHandler(url: url).perform([request])
            } catch {
                return nil
            }
            return request.results?.compactMap { $0.topCandidates(1).first?.string }.joined(separator: "\n")
        }.value
    }
}

/// Accepts files and pictures dropped on the shelf.
enum ShelfDrop {
    static let types: [UTType] = [.fileURL, .image]

    @MainActor
    static func accept(_ providers: [NSItemProvider], into shelf: ShelfStore) -> Bool {
        var accepted = false
        for provider in providers {
            if provider.hasItemConformingToTypeIdentifier(UTType.fileURL.identifier) {
                accepted = true
                _ = provider.loadObject(ofClass: URL.self) { url, _ in
                    guard let url else { return }
                    Task { @MainActor in shelf.add([url]) }
                }
            } else if provider.hasItemConformingToTypeIdentifier(UTType.image.identifier) {
                // A picture dragged from a browser has no file yet; save one.
                accepted = true
                let directory = shelf.droppedFilesDirectory
                let suggestedName = provider.suggestedName
                provider.loadFileRepresentation(forTypeIdentifier: UTType.image.identifier) { temporary, _ in
                    guard let temporary else { return }
                    let name = suggestedName.map { $0 + "." + temporary.pathExtension } ?? temporary.lastPathComponent
                    let destination = directory.appendingPathComponent(UUID().uuidString.prefix(6) + "-" + name)
                    guard (try? FileManager.default.copyItem(at: temporary, to: destination)) != nil else { return }
                    Task { @MainActor in shelf.add([destination]) }
                }
            }
        }
        return accepted
    }
}
